version: "3.3"

services:
  traefik:
    image: "traefik:munster"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.directory=/conf/"
      - "--providers.file.watch=true"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf:/conf"
      - "./ssl:/ssl"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`loc.zzizily.com)"
      - "traefik.http.routers.whoami.tls=true"
